USE wfrmls08
DROP TABLE IF EXISTS listings;

CREATE TABLE listings (					
	PRIMARY KEY (listno),			
	acres  		FLOAT (5,2) UNSIGNED,		
	additinfo	VARCHAR(255),			
	area		SMALLINT UNSIGNED,		
	backdim		TINYINT UNSIGNED,		
	bsmntfin	TINYINT UNSIGNED,		
	city		VARCHAR(255),	
	compbac		FLOAT(3,2),		
	compdays	SMALLINT UNSIGNED,		
	compsac		FLOAT(3,2),		
	contact		VARCHAR(30),		
	contph1		VARCHAR(14),		
	contph2		VARCHAR(14),		
	contractdt	DATE,			
	county		VARCHAR(255),
	crprtcap	TINYINT UNSIGNED,		
	daysonmkt	SMALLINT UNSIGNED,		
	deck		TINYINT UNSIGNED,		
	dirpost		CHAR(1),
	dirpre		CHAR(1),	
	dvr		CHAR(0) NULL,		
	entrdby		VARCHAR(255),		
	entrydt		DATE,			
	ewcoord		SMALLINT UNSIGNED,		
	expdtdisp	DATE,			
	frontage	TINYINT UNSIGNED,		
	garagcap	TINYINT UNSIGNED,		
	hoafee		TINYINT UNSIGNED,		
	housenbr	SMALLINT UNSIGNED,		
	irregular	CHAR(0) NULL,		
	latitude	FLOAT,		
	listdt		DATE,			
	listno	 	INT NOT NULL,			
	listtype	CHAR(3),		
	longitude	FLOAT,		
	lstprice	DOUBLE UNSIGNED,		
	nscoord		SMALLINT UNSIGNED,		
	numdish	TINYINT UNSIGNED,		
	numdispose	TINYINT UNSIGNED,		
	numovrng	TINYINT UNSIGNED,		
	numrefg	TINYINT UNSIGNED,		
	offmktdt	DATE,			
	openhsedt	DATE,			
	owner		VARCHAR(255),		
	p1bar		CHAR(0) NULL,		
	p1bed		TINYINT UNSIGNED,		
	p1bthfull	TINYINT UNSIGNED,		
	p1bthhalf	TINYINT UNSIGNED,		
	p1bthtq		TINYINT UNSIGNED,		
	p1famden	CHAR(0) NULL,		
	p1fire		TINYINT UNSIGNED,		
	p1formal	CHAR(0) NULL,		
	p1kitch		CHAR(0) NULL,		
	p1laundry	CHAR(0) NULL,		
	p1rent		TINYINT UNSIGNED,		
	p1semiform	CHAR(0) NULL,		
	p1sqf		SMALLINT UNSIGNED,		
	p2bar		CHAR(0) NULL,		
	p2bed		TINYINT UNSIGNED,		
	p2bthfull	TINYINT UNSIGNED,		
	p2bthhalf	TINYINT UNSIGNED,		
	p2bthtq		TINYINT UNSIGNED,		
	p2famden	CHAR(0) NULL,		
	p2fire		TINYINT UNSIGNED,		
	p2formal	CHAR(0) NULL,		
	p2kitch		CHAR(0) NULL,		
	p2laundry	CHAR(0) NULL,		
	p2rent		TINYINT UNSIGNED,		
	p2semiform	CHAR(0) NULL,		
	p2sqf		SMALLINT UNSIGNED,		
	p3bar		CHAR(0) NULL,		
	p3bed		TINYINT UNSIGNED,		
	p3bthfull	TINYINT UNSIGNED,		
	p3bthhalf	TINYINT UNSIGNED,		
	p3bthtq		TINYINT UNSIGNED,		
	p3famden	CHAR(0) NULL,		
	p3fire		TINYINT UNSIGNED,		
	p3formal	CHAR(0) NULL,		
	p3kitch		CHAR(0) NULL,		
	p3laundry	CHAR(0) NULL,		
	p3rent		TINYINT UNSIGNED,		
	p3semiform	CHAR(0) NULL,		
	p3sqf		SMALLINT UNSIGNED,		
	p4bar		CHAR(0) NULL,		
	p4bed		TINYINT UNSIGNED,		
	p4bthfull	TINYINT UNSIGNED,		
	p4bthhalf	TINYINT UNSIGNED,		
	p4bthtq		TINYINT UNSIGNED,		
	p4famden	CHAR(0) NULL,		
	p4fire		TINYINT UNSIGNED,		
	p4formal	CHAR(0) NULL,		
	p4kitch		CHAR(0) NULL,		
	p4laundry	CHAR(0) NULL,		
	p4rent		TINYINT UNSIGNED,		
	p4semiform	CHAR(0) NULL,		
	p4sqf		SMALLINT UNSIGNED,		
	p5bar		CHAR(0) NULL,		
	p5bed		TINYINT UNSIGNED,		
	p5bthfull	TINYINT UNSIGNED,		
	p5bthhalf	TINYINT UNSIGNED,		
	p5bthtq		TINYINT UNSIGNED,		
	p5famden	CHAR(0) NULL,		
	p5fire		TINYINT UNSIGNED,		
	p5formal	CHAR(0) NULL,		
	p5kitch		CHAR(0) NULL,		
	p5laundry	CHAR(0) NULL,		
	p5rent		TINYINT UNSIGNED,		
	p5semiform	CHAR(0) NULL,		
	p5sqf		SMALLINT UNSIGNED,		
	patio		TINYINT UNSIGNED,		
	possess		VARCHAR(255),		
	proptype	VARCHAR(255),		
	publicid	VARCHAR(255),
	quadrant	CHAR(2),
	reinstdt	DATE,			
	remarks		VARCHAR(255),		
	rmpricelow	TINYINT UNSIGNED,		
	rstrct		CHAR(0) NULL,		
	schother	VARCHAR(255),
	sidedim		TINYINT UNSIGNED,		
	slagentid	INT UNSIGNED,
	slagentpub	VARCHAR(255),
	sldofcid	INT UNSIGNED,
	slrpaidcns	TINYINT UNSIGNED,		
	solddt	DATE,			
	soldprice	DOUBLE UNSIGNED,		
	soldterms		VARCHAR(255),
	statcode	TINYINT UNSIGNED,		
	statdate	DATE,			
	state		VARCHAR(255),
	status		VARCHAR(14),		
	street	VARCHAR(30),
	strtype	VARCHAR(10),
	style		VARCHAR(30),		
	subagncy	CHAR(0) NULL,		
	subdiv	VARCHAR(30),
	taxes		SMALLINT UNSIGNED,		
	taxid		VARCHAR(255),		
	timeclause	VARCHAR(255),		
	totairelc	TINYINT UNSIGNED,		
	totairevp	TINYINT UNSIGNED,		
	totairgas	TINYINT UNSIGNED,		
	totairpmp	TINYINT UNSIGNED,		
	totairsol	TINYINT UNSIGNED,		
	totairwelc	TINYINT UNSIGNED,		
	totbar		TINYINT UNSIGNED,		
	totbed		TINYINT UNSIGNED,		
	totbthful	TINYINT UNSIGNED,		
	totbthhal	TINYINT UNSIGNED,		
	totbth		TINYINT UNSIGNED,		
	totbthtq	TINYINT UNSIGNED,		
	totfamrm	TINYINT UNSIGNED,		
	totfire		TINYINT UNSIGNED,		
	totformal	TINYINT UNSIGNED,		
	totkitch	TINYINT UNSIGNED,		
	totldy		TINYINT UNSIGNED,		
	totrent		TINYINT UNSIGNED,		
	totsemi		TINYINT UNSIGNED,		
	totsqf		SMALLINT UNSIGNED,		
	totwinevp	TINYINT UNSIGNED,		
	undrcnst	CHAR(0) NULL,	
	unitnbr	SMALLINT UNSIGNED,
	winele1		TINYINT UNSIGNED,		
	winele2		TINYINT UNSIGNED,		
	winele3		TINYINT UNSIGNED,		
	winele4		TINYINT UNSIGNED,		
	winevp1		TINYINT UNSIGNED,		
	winevp2		TINYINT UNSIGNED,		
	winevp3		TINYINT UNSIGNED,		
	winevp4		TINYINT UNSIGNED,		
	withdrdt	DATE,			
	yearblt		YEAR,		
	zip		MEDIUMINT UNSIGNED,
	zoning		VARCHAR(255)
);

